# Generated by Django 5.2.1 on 2025-05-21 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lista", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Todo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Título")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("deadline", models.DateField(verbose_name="Data de entrega")),
                ("finished_at", models.DateField(null=True)),
            ],
            options={
                "ordering": ["deadline"],
            },
        ),
        migrations.DeleteModel(
            name="lista",
        ),
    ]
